### PR TITLE
High TLS cipher strength for Postfix

### PR DESCRIPTION
**Pull request by aykevl**

### CODE REVIEW

**Comment by mrngm** [comment]
According to Postfix' documentation, the ciphers used will be OpenSSL's `HIGH` ciphers, or as [postconf tls_high_cipherlist](http://www.postfix.org/postconf.5.html#tls_high_cipherlist) puts it:
```
# postconf tls_high_cipherlist
tls_high_cipherlist = aNULL:-aNULL:ALL:!EXPORT:!LOW:!MEDIUM:+RC4:@STRENGTH
```

What's the rationale behind this? I understand it's for opportunistic TLS for receiving e-mail, but this cipher list is not considered strong, at all.

**Comment by bwesterb** [comment]
Als ik mij niet vergis is hij wel sterker dan de *default*.  Overnemen?  @aykevl @mrngm

**Comment by aykevl** [comment]
De default is medium, dus dan zal dit wel beter zijn. Bij mij geeft hij minder warnings met deze configuratie.

**Comment by bwesterb** [comment]
Staat online.

**Pull request merged**
