### PR TITLE
balans.html: typo 'veschuldigd' gefixt

### PR DESCRIPTION
**Pull request by mrngm**

### CODE REVIEW

**Comment by mrngm** [comment]
Moet het ook nog in de `.po`-bestanden aangepast worden?

```
$ git grep veschuldigd
locale/de/LC_MESSAGES/django.po:"ons nog  <strong>€&nbsp;%(bedrag)s</strong> veschuldigd.\n"
locale/en/LC_MESSAGES/django.po:"ons nog  <strong>€&nbsp;%(bedrag)s</strong> veschuldigd.\n"
locale/en_PI/LC_MESSAGES/django.po:"ons nog  <strong>€&nbsp;%(bedrag)s</strong> veschuldigd.\n"
```

**Comment by bwesterb** [comment]
`./manage.py makemessages --all`

**Comment by mrngm** [comment]
So I tried running this through the `vagrant` method. Unfortunately, it said that it couldn't find something.

```
Traceback (most recent call last):
  File "./manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'
```

I first thought `vagrant up` did not succeed due to disk space issues, but after `vagrant destroy` and `vagrant up`, the following error occurs:

```
#<Thread:0x000055d5de7e11c0@/opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/batch_action.rb:71 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	106: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
	105: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/machine.rb:188:in `action'
	104: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/machine.rb:188:in `call'
	103: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/environment.rb:592:in `lock'
	102: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/machine.rb:202:in `block in action'
	101: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/machine.rb:227:in `action_raw'
	100: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `run'
	 99: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/util/busy.rb:19:in `busy'
	 98: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `block in run'
	 97: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/builder.rb:116:in `call'
	 96: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 95: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
	 94: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 93: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/builtin/call.rb:53:in `call'
	 92: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `run'
	 91: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/util/busy.rb:19:in `busy'
	 90: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `block in run'
	 89: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/builder.rb:116:in `call'
	 88: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 87: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	 86: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 85: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
	 84: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 83: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	 82: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 81: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	 80: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 79: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/builtin/call.rb:53:in `call'
	 78: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `run'
	 77: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/util/busy.rb:19:in `busy'
	 76: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `block in run'
	 75: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/builder.rb:116:in `call'
	 74: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 73: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	 72: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 71: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
	 70: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 69: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/plugins/providers/virtualbox/action/customize.rb:40:in `call'
	 68: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 67: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/builtin/prepare_clone.rb:15:in `call'
	 66: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 65: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/plugins/providers/virtualbox/action/prepare_clone_snapshot.rb:17:in `call'
	 64: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 63: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/plugins/providers/virtualbox/action/import.rb:13:in `call'
	 62: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/plugins/providers/virtualbox/action/import.rb:74:in `import'
	 61: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 60: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/plugins/providers/virtualbox/action/discard_state.rb:15:in `call'
	 59: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 58: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/plugins/providers/virtualbox/action/match_mac_address.rb:19:in `call'
	 57: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 56: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	 55: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 54: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
	 53: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 52: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	 51: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 50: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/builtin/box_check_outdated.rb:79:in `call'
	 49: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 48: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/builtin/call.rb:53:in `call'
	 47: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `run'
	 46: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/util/busy.rb:19:in `busy'
	 45: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `block in run'
	 44: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/builder.rb:116:in `call'
	 43: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 42: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	 41: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 40: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/builtin/call.rb:53:in `call'
	 39: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `run'
	 38: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/util/busy.rb:19:in `busy'
	 37: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `block in run'
	 36: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/builder.rb:116:in `call'
	 35: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 34: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	 33: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 32: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/builtin/call.rb:53:in `call'
	 31: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `run'
	 30: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/util/busy.rb:19:in `busy'
	 29: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `block in run'
	 28: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/builder.rb:116:in `call'
	 27: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 26: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	 25: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 24: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
	 23: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 22: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/plugins/providers/virtualbox/action/clean_machine_folder.rb:17:in `call'
	 21: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 20: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/plugins/providers/virtualbox/action/set_name.rb:50:in `call'
	 19: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 18: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/plugins/providers/virtualbox/action/clear_forwarded_ports.rb:15:in `call'
	 17: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 16: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/builtin/provision.rb:103:in `call'
	 15: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/builtin/provision.rb:103:in `each'
	 14: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/builtin/provision.rb:126:in `block in call'
	 13: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/builtin/provision.rb:126:in `call'
	 12: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/environment.rb:504:in `hook'
	 11: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `run'
	 10: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/util/busy.rb:19:in `busy'
	  9: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `block in run'
	  8: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/builder.rb:116:in `call'
	  7: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	  6: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	  5: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:95:in `call'
	  4: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/builtin/provision.rb:138:in `run_provisioner'
	  3: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/plugins/provisioners/salt/provisioner.rb:24:in `provision'
	  2: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/plugins/provisioners/salt/provisioner.rb:405:in `call_highstate'
	  1: from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/plugins/communicators/ssh/communicator.rb:267:in `sudo'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.2/plugins/communicators/ssh/communicator.rb:257:in `execute': The SSH command responded with a non-zero exit status. Vagrant (Vagrant::Errors::VagrantError)
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

After some scrolling back, it looks like `MechanicalSoup` might be cause of this problem:

```
----------
          ID: MechanicalSoup
    Function: pip.installed
      Result: False
     Comment: Failed to install packages: MechanicalSoup. Error: Downloading/unpacking MechanicalSoup
                Downloading MechanicalSoup-0.10.0.tar.gz
                Running setup.py (path:/tmp/pip-build-8raql7r_/MechanicalSoup/setup.py) egg_info for package MechanicalSoup
                  /usr/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'python_requires'
                    warnings.warn(msg)
                  your setuptools is too old (<12)
                  setuptools_scm functionality is degraded
                  zip_safe flag not set; analyzing archive contents...
[..]
              Downloading/unpacking lxml (from MechanicalSoup)
                Running setup.py (path:/tmp/pip-build-8raql7r_/lxml/setup.py) egg_info for package lxml
                  Building lxml version 4.1.1.
                  Building without Cython.
                  ERROR: b'/bin/sh: 1: xslt-config: not found\n'
                  ** make sure the development packages of libxml2 and libxslt are installed **
[..]
                  Using build configuration of libxslt
                  building 'lxml.etree' extension
                  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -DCYTHON_CLINE_IN_TRACEBACK=1 -Isrc -Isrc/lxml/includes -I/usr/include/python3.4m -c src/lxml/etree.c -o build/temp.linux-x86_64-3.4/src/lxml/etree.o -w
                  In file included from src/lxml/etree.c:619:0:
                  src/lxml/includes/etree_defs.h:14:31: fatal error: libxml/xmlversion.h: No such file or directory
                   #include "libxml/xmlversion.h"
                                                 ^
                  compilation terminated.
                  Compile failed: command 'x86_64-linux-gnu-gcc' failed with exit status 1
                  cc -I/usr/include/libxml2 -c /tmp/xmlXPathInit7fv57iup.c -o tmp/xmlXPathInit7fv57iup.o
                  /tmp/xmlXPathInit7fv57iup.c:1:26: fatal error: libxml/xpath.h: No such file or directory
                   #include "libxml/xpath.h"
                                            ^
                  compilation terminated.
                  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
[..]
```

So I ran `vagrant up` again, failed with rougly the same error message, ran `vagrant up` again, and tried to execute `./manage.py makemessages --all`:

```
infra@vagrant-sankhara:/vagrant$ ./manage.py makemessages --all
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 533, in handle
    return self.handle_noargs(**options)
  File "/usr/lib/python2.7/dist-packages/django/core/management/commands/makemessages.py", line 283, in handle_noargs
    potfiles = self.build_potfiles()
  File "/usr/lib/python2.7/dist-packages/django/core/management/commands/makemessages.py", line 303, in build_potfiles
    f.process(self, self.domain)
  File "/usr/lib/python2.7/dist-packages/django/core/management/commands/makemessages.py", line 95, in process
    with open(os.path.join(self.dirpath, thefile), "w") as fp:
IOError: [Errno 13] Toegang geweigerd: u'./coding-style.txt.py'
infra@vagrant-sankhara:/vagrant$ ls -ahl
total 76K
drwxr-xr-x  1 vagrant vagrant 4.0K Feb  6 16:07 .
drwxr-xr-x 23 root    root    4.0K Feb  6 17:02 ..
drwxr-xr-x  1 vagrant vagrant 4.0K Feb  6 16:06 bin
-rw-r--r--  1 vagrant vagrant  615 Feb  6 16:06 coding-style.txt
drwxr-xr-x  1 vagrant vagrant 4.0K Feb  6 17:04 .git
-rw-r--r--  1 vagrant vagrant  111 Feb  6 16:06 .gitignore
-rw-r--r--  1 vagrant vagrant  214 Feb  6 16:06 .isort.cfg
drwxr-xr-x  1 vagrant vagrant 4.0K Feb  6 17:03 kn
drwxr-xr-x  1 vagrant vagrant 4.0K Feb  6 16:06 locale
-rwxr-xr-x  1 vagrant vagrant  245 Feb  6 16:06 manage.py
drwxr-xr-x  1 vagrant vagrant 4.0K Feb  6 16:06 media
-rw-r--r--  1 vagrant vagrant 7.6K Feb  6 16:06 README.md
drwxr-xr-x  1 vagrant vagrant 4.0K Feb  6 16:06 salt
-rw-r--r--  1 vagrant vagrant  235 Feb  6 16:06 .travis.yml
drwxr-xr-x  1 vagrant vagrant 4.0K Feb  6 16:14 utils
drwxr-xr-x  1 vagrant vagrant 4.0K Feb  6 16:07 .vagrant
-rw-r--r--  1 vagrant vagrant 5.5K Feb  6 16:06 Vagrantfile
```

**Comment by bwesterb** [comment]
Een `sudo` lost dat op.  Ik heb `makemessages` gedraaid op de huidige master in https://github.com/karpenoktem/kninfra/commit/c437e28b959d69b4b03126dfbf124c3ad78d628c

**Comment by mrngm** [comment]
Righto, commit op deze branch binnengehaald, in de Vagrant-machine:

```
infra@vagrant-sankhara:/vagrant$ sudo ./manage.py makemessages --all
processing locale en_PI
processing locale en
processing locale de
infra@vagrant-sankhara:/vagrant$ 
```

**Comment by bwesterb** [comment]
Merci.

**Pull request merged**
